import Head from "next/head";
import styles from "../styles/Home.module.css";
import { signInWithGoogle } from "../lib/signIn";
import Link from "next/link";

const DashboardButton = () => (
  <>
    <Link href="/dashboard" passHref>
      <button className="bg-[#3A6344] hover:bg-blue-700 text-white py-3">
        Continue To Dashboard
      </button>
    </Link>
  </>
);

const CompleteSignUpButton = () => (
  <>
    <Link href="/signup" passHref>
      <button className="bg-[#3A6344] hover:bg-blue-700 text-white py-3">
        Complete Sign Up
      </button>
    </Link>
  </>
);

const   Root = ({ user }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <div className="min-h-screen w-screen bg-[#F2EAE8] m-0 p-0 font-hk">
          <div className="kai-container my-6 mx-12">
            <span className="text-xl ">Kai</span>
          </div>
          <div className="svg-container">{/* add bubbles svg here */}</div>
          <div className="content-container my-20 mx-12 relative">
            <div className="w-[80%]">
              <span className=" text-6xl">
                Track your health easily with us
              </span>
            </div>
            <div className="w-[80%] my-8">
              <p className="font-semi-bold font-hk">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Non
                obcaecati, modi doloremque consequuntur eaque optio libero
                commodi nam quasi aperiam .
              </p>
            </div>
            <div className="buttons-container flex flex-col justify-center font-bold w-1/3 font-hk">
              {user === null ? (
                <>
                  <button
                    className="bg-[#3A6344] hover:bg-blue-700 text-white py-3"
                    onClick={signInWithGoogle}
                  >
                    Register Yourself
                  </button>
                  <span className="my-2 text-center">OR</span>
                  <button className="text-[#3A6344] py-1">
                    Register as a Hospital
                  </button>
                </>
              ) : user.firstName ? (
                <DashboardButton />
              ) : (
                <CompleteSignUpButton />
              )}
            </div>
          </div>
        </div>
        <div className="min-h-screen w-[150vh] bg-purple-400"></div>
      </div>
    </div>
  );
};

export default Root;
