import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Bubbles from "../public/assets/bubbles.svg";
import { UserContext } from "../lib/context";
import { useContext } from "react";
import Link from "next/link"
import { signInWithGoogle } from "../lib/signIn";

const DashboardButton = () => (
    <>
        <Link href="/dashboard" passHref>
            <button className="bg-[#3A6344] hover:bg-blue-700 text-white py-3">
                Continue To Dashboard
            </button>
        </Link>
    </>
);

const CompleteSignUpButton = () => (
    <>
        <Link href="/signup" passHref>
            <button className="bg-yellow-500 rounded-lg shadow-md text-white py-3">
                Complete Sign Up
            </button>
        </Link>
    </>
);

// import Health from "../public/assets/health_care_1";

export default function Home() {
    const { user, username } = useContext(UserContext);
    return (
        <div className={styles.container}>
            <Head>
                <title>Kai</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           
            <div className="flex bg-gradient-to-t from-red-500 to-amber-600 main-container-1">
                <div className="min-h-screen w-screen bg-[#F2EAE8] m-0 p-0 font-hk">
                    <div className="kai-container my-6 mx-12">
                        <span className="text-xl ">Kai</span>
                    </div>
                    <div className="svg-container">
                        <div className="absolute left-2/4 top-20 h-16 aspect-square hidden">
                            <Image src={Bubbles} layout="fill" alt=""></Image>
                        </div>
                    </div>
                    <div className="content-container my-10 mx-12 relative p-4 text-center sm:text-left md:w-[70%] ">
                        <div className="w-[100%] md:w-[80%]">
                            <span className="text-4xl sm:text-5xl lg:text-6xl">
                                Track your health easily with Kai
                            </span>
                        </div>
                        <div className="w-[100%] my-8 sm:w-[70%]">
                            <p className="font-semi-bold font-hk">
                                Kai is a network of records and a hub for Open
                                Protocols defined for delivery of digital health
                                services.
                            </p>
                            <p className="font-semi-bold font-hk my-6">
                                Millions of Hospitals, medical professionals and
                                researchers are connected with our network
                            </p>
                        </div>
                        <div className="buttons-container flex flex-col justify-center font-bold w-1/3 font-hk">
                            {user === null ? (
                                <>
                                    <button
                                        className="bg-yellow-500 rounded-lg shadow-md text-white py-3"
                                        onClick={signInWithGoogle}
                                    >
                                        Register Yourself
                                    </button>
                                    <span className="my-2 text-center">OR</span>
                                    <button className="text-[#3A6344] py-1">
                                        Register as a Hospital
                                    </button>
                                </>
                            ) : user.firstName ? (
                                <DashboardButton />
                            ) : (
                                <CompleteSignUpButton />
                            )}
                        </div>
                    </div>
                </div>
                <div className="bg-gradient-to-t from-orange-400 to-red-400 hidden md:block min-h-screen w-[100vh] "></div>
            </div>
        </div>
    );
}
